channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.5=py39h3b20f71_0
  - netcdf4=1.6.1=nompi_py39h34fa13a_100
  - dask=2022.9.2=pyhd8ed1ab_0
  - xarray=2022.9.0=pyhd8ed1ab_0
  - bottleneck=1.3.5=py39h5d4886f_0
  - geopandas=0.12.2=pyhd8ed1ab_0
  - shapely=1.8.4=py39he0923fe_0
  - scipy=1.9.3=py39he11b74f_0
  - pygeos=0.13=py39h6f18ba6_1
  #Required by ArcGIS API for Python
  - matplotlib-base=3.6.2=py39haf65ace_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - pandas=1.5.2=py39h2ba5b7c_2
  - pip:
    #Required by ArcGIS API for Python
    - arcgis==2.0.1
    - psycopg2==2.9.3
    - azure-storage-blob==12.9
    - ./resources/GDAL-3.4.3-cp39-cp39-win_amd64.whl
    - ./resources/rasterio-1.2.10-cp39-cp39-win_amd64.whl
